import type { Role, Skill } from '../../types/career'

/**
 * Isi awal tabel `skills` dan `roles`.
 *
 * Sebelumnya data ini hidup sebagai konstanta di `composables/useRoleMatcher.ts`.
 * Sekarang MySQL yang jadi sumber kebenaran — file ini hanya benih pertamanya,
 * supaya database kosong bisa langsung terisi tanpa entri manual. Setelah
 * di-seed, perubahan katalog boleh dilakukan langsung di database; `db:seed`
 * memakai upsert sehingga menjalankannya ulang tidak menghapus baris yang
 * sudah ada.
 *
 * Angka gaji adalah perkiraan gaji BERSIH bulanan pasar Indonesia untuk level
 * pemula–menengah. Dipakai sebagai ancar-ancar awal; begitu lowongan asli masuk
 * lewat Google Jobs, angka pasarnya bisa dibandingkan dengan yang nyata.
 */

export const SKILL_SEED: Skill[] = [
  // ── Dasar Kerja ────────────────────────────────────────────────────────
  { id: 'komunikasi', label: 'Komunikasi', category: 'Dasar Kerja', aliases: ['communication', 'komunikatif'] },
  { id: 'excel', label: 'Excel / Spreadsheet', category: 'Dasar Kerja', aliases: ['excel', 'spreadsheet', 'google sheets', 'microsoft excel'] },
  { id: 'admin', label: 'Administrasi', category: 'Dasar Kerja', aliases: ['administrasi', 'administrative', 'filing', 'tata usaha'] },
  { id: 'bahasa-inggris', label: 'Bahasa Inggris', category: 'Dasar Kerja', aliases: ['english', 'bahasa inggris', 'toefl', 'ielts'] },
  { id: 'riset', label: 'Riset & analisis informasi', category: 'Dasar Kerja', aliases: ['research', 'riset', 'analisis'] },
  { id: 'manajemen-waktu', label: 'Manajemen waktu', category: 'Dasar Kerja', aliases: ['time management', 'manajemen waktu', 'multitasking'] },
  { id: 'layanan-pelanggan', label: 'Layanan pelanggan', category: 'Dasar Kerja', aliases: ['customer service', 'customer support', 'layanan pelanggan', 'cs'] },
  { id: 'presentasi', label: 'Presentasi', category: 'Dasar Kerja', aliases: ['presentation', 'presentasi', 'public speaking'] },

  // ── Desain & Konten ────────────────────────────────────────────────────
  { id: 'copywriting', label: 'Copywriting', category: 'Desain & Konten', aliases: ['copywriting', 'copywriter', 'menulis konten', 'content writing'] },
  { id: 'canva', label: 'Canva', category: 'Desain & Konten', aliases: ['canva'] },
  { id: 'figma', label: 'Figma', category: 'Desain & Konten', aliases: ['figma', 'sketch app'] },
  { id: 'photoshop', label: 'Photoshop / Illustrator', category: 'Desain & Konten', aliases: ['photoshop', 'illustrator', 'adobe', 'coreldraw'] },
  { id: 'video-editing', label: 'Edit video', category: 'Desain & Konten', aliases: ['premiere', 'capcut', 'after effects', 'video editing', 'edit video', 'davinci'] },
  { id: 'fotografi', label: 'Fotografi', category: 'Desain & Konten', aliases: ['fotografi', 'photography', 'foto produk'] },
  { id: 'storytelling', label: 'Storytelling & naskah', category: 'Desain & Konten', aliases: ['storytelling', 'naskah', 'script', 'copy'] },

  // ── Digital Marketing ──────────────────────────────────────────────────
  { id: 'social-media', label: 'Kelola media sosial', category: 'Digital Marketing', aliases: ['social media', 'media sosial', 'instagram', 'tiktok', 'admin sosmed'] },
  { id: 'seo', label: 'SEO', category: 'Digital Marketing', aliases: ['seo', 'search engine optimization'] },
  { id: 'meta-ads', label: 'Meta Ads', category: 'Digital Marketing', aliases: ['meta ads', 'facebook ads', 'instagram ads', 'fb ads'] },
  { id: 'google-ads', label: 'Google Ads', category: 'Digital Marketing', aliases: ['google ads', 'google adwords', 'sem'] },
  { id: 'content-planning', label: 'Perencanaan konten', category: 'Digital Marketing', aliases: ['content plan', 'content calendar', 'perencanaan konten', 'kalender konten'] },
  { id: 'email-marketing', label: 'Email marketing', category: 'Digital Marketing', aliases: ['email marketing', 'mailchimp', 'newsletter'] },

  // ── Data ───────────────────────────────────────────────────────────────
  { id: 'sql', label: 'SQL', category: 'Data', aliases: ['sql', 'mysql', 'postgresql', 'bigquery'] },
  { id: 'python', label: 'Python', category: 'Data', aliases: ['python', 'pandas', 'numpy'] },
  { id: 'visualisasi', label: 'Visualisasi data', category: 'Data', aliases: ['tableau', 'power bi', 'looker', 'data studio', 'visualisasi data'] },
  { id: 'statistik', label: 'Statistik dasar', category: 'Data', aliases: ['statistik', 'statistics', 'ab test', 'a/b testing'] },
  { id: 'data-cleaning', label: 'Rapikan & olah data', category: 'Data', aliases: ['data cleaning', 'data entry', 'olah data', 'etl'] },

  // ── Teknologi ──────────────────────────────────────────────────────────
  { id: 'html-css', label: 'HTML & CSS', category: 'Teknologi', aliases: ['html', 'css', 'tailwind', 'bootstrap'] },
  { id: 'javascript', label: 'JavaScript', category: 'Teknologi', aliases: ['javascript', 'typescript', 'js'] },
  { id: 'react', label: 'React / Vue', category: 'Teknologi', aliases: ['react', 'vue', 'nextjs', 'next.js', 'nuxt', 'angular'] },
  { id: 'nodejs', label: 'Node.js / backend', category: 'Teknologi', aliases: ['node', 'node.js', 'express', 'laravel', 'django', 'php'] },
  { id: 'database', label: 'Database', category: 'Teknologi', aliases: ['database', 'mongodb', 'basis data'] },
  { id: 'api', label: 'REST API', category: 'Teknologi', aliases: ['api', 'rest api', 'endpoint'] },
  { id: 'git', label: 'Git', category: 'Teknologi', aliases: ['git', 'github', 'gitlab', 'version control'] },
  { id: 'testing', label: 'Pengujian / QA', category: 'Teknologi', aliases: ['qa', 'testing', 'quality assurance', 'test case', 'bug report'] },

  // ── Bisnis & Keuangan ──────────────────────────────────────────────────
  { id: 'akuntansi', label: 'Akuntansi dasar', category: 'Bisnis & Keuangan', aliases: ['akuntansi', 'accounting', 'jurnal umum'] },
  { id: 'pembukuan', label: 'Pembukuan', category: 'Bisnis & Keuangan', aliases: ['pembukuan', 'bookkeeping', 'laporan keuangan'] },
  { id: 'pajak', label: 'Perpajakan', category: 'Bisnis & Keuangan', aliases: ['pajak', 'ppn', 'pph', 'e-faktur'] },
  { id: 'sales', label: 'Penjualan', category: 'Bisnis & Keuangan', aliases: ['sales', 'penjualan', 'marketing lapangan', 'canvassing'] },
  { id: 'crm', label: 'CRM', category: 'Bisnis & Keuangan', aliases: ['crm', 'salesforce', 'hubspot'] },
  { id: 'manajemen-stok', label: 'Manajemen stok', category: 'Bisnis & Keuangan', aliases: ['inventory', 'stok', 'gudang', 'warehouse'] },
]

/**
 * `searchQuery` adalah istilah yang benar-benar dipakai lowongan asli di
 * Indonesia — sering campur Inggris. Dipisah dari `title` supaya label yang
 * dibaca user tetap bahasa Indonesia sementara hasil pencariannya tetap kaya.
 */
export const ROLE_SEED: (Role & { searchQuery: string })[] = [
  {
    id: 'admin-sosmed',
    title: 'Admin Media Sosial',
    field: 'Digital & Kreatif',
    salaryMin: 3_500_000,
    salaryTypical: 4_500_000,
    entryFriendly: true,
    remoteFriendly: true,
    timeToEntry: '1–2 bulan',
    skills: ['social-media', 'canva', 'copywriting', 'content-planning', 'manajemen-waktu'],
    description: 'Mengelola akun media sosial brand: menyusun jadwal konten, membuat materi sederhana, dan membalas komentar.',
    searchQuery: 'admin media sosial social media officer',
  },
  {
    id: 'content-writer',
    title: 'Content Writer',
    field: 'Digital & Kreatif',
    salaryMin: 4_000_000,
    salaryTypical: 6_000_000,
    entryFriendly: true,
    remoteFriendly: true,
    timeToEntry: '1–3 bulan',
    skills: ['copywriting', 'seo', 'riset', 'storytelling', 'bahasa-inggris'],
    description: 'Menulis artikel, halaman produk, dan materi promosi yang mudah ditemukan di mesin pencari.',
    searchQuery: 'content writer copywriter penulis konten',
  },
  {
    id: 'desainer-grafis',
    title: 'Desainer Grafis',
    field: 'Digital & Kreatif',
    salaryMin: 4_000_000,
    salaryTypical: 6_500_000,
    entryFriendly: true,
    remoteFriendly: true,
    timeToEntry: '3–5 bulan',
    skills: ['canva', 'figma', 'photoshop', 'storytelling'],
    description: 'Membuat materi visual untuk promosi, kemasan, dan media sosial.',
    searchQuery: 'desainer grafis graphic designer',
  },
  {
    id: 'video-editor',
    title: 'Video Editor',
    field: 'Digital & Kreatif',
    salaryMin: 4_500_000,
    salaryTypical: 7_500_000,
    entryFriendly: true,
    remoteFriendly: true,
    timeToEntry: '2–4 bulan',
    skills: ['video-editing', 'storytelling', 'fotografi', 'canva'],
    description: 'Menyunting video pendek untuk TikTok, Reels, dan YouTube — kebutuhan yang sedang tinggi.',
    searchQuery: 'video editor editor konten',
  },
  {
    id: 'cs-online',
    title: 'Customer Service Online',
    field: 'Bisnis & Operasional',
    salaryMin: 3_500_000,
    salaryTypical: 4_800_000,
    entryFriendly: true,
    remoteFriendly: true,
    timeToEntry: 'Kurang dari 1 bulan',
    skills: ['layanan-pelanggan', 'komunikasi', 'manajemen-waktu', 'crm'],
    description: 'Menjawab pertanyaan pelanggan lewat chat dan telepon. Pintu masuk tercepat kalau butuh pemasukan segera.',
    searchQuery: 'customer service online admin chat',
  },
  {
    id: 'admin-toko-online',
    title: 'Admin Toko Online',
    field: 'Bisnis & Operasional',
    salaryMin: 3_800_000,
    salaryTypical: 5_500_000,
    entryFriendly: true,
    remoteFriendly: true,
    timeToEntry: 'Kurang dari 1 bulan',
    skills: ['manajemen-stok', 'admin', 'layanan-pelanggan', 'excel', 'social-media'],
    description: 'Mengurus pesanan, stok, dan pengiriman di marketplace seperti Shopee, Tokopedia, dan TikTok Shop.',
    searchQuery: 'admin toko online admin marketplace e-commerce',
  },
  {
    id: 'data-entry',
    title: 'Staf Data Entry',
    field: 'Bisnis & Operasional',
    salaryMin: 3_200_000,
    salaryTypical: 4_200_000,
    entryFriendly: true,
    remoteFriendly: true,
    timeToEntry: 'Kurang dari 1 bulan',
    skills: ['excel', 'admin', 'data-cleaning', 'manajemen-waktu'],
    description: 'Memasukkan dan merapikan data ke sistem. Ritmenya stabil dan syarat masuknya paling ringan.',
    searchQuery: 'data entry staff admin data',
  },
  {
    id: 'virtual-assistant',
    title: 'Virtual Assistant (klien luar negeri)',
    field: 'Bisnis & Operasional',
    salaryMin: 5_000_000,
    salaryTypical: 9_000_000,
    entryFriendly: true,
    remoteFriendly: true,
    timeToEntry: '1–2 bulan',
    skills: ['bahasa-inggris', 'admin', 'manajemen-waktu', 'excel', 'komunikasi'],
    description: 'Membantu pekerjaan administratif klien luar negeri. Bayarannya jauh lebih tinggi kalau bahasa Inggrismu jalan.',
    searchQuery: 'virtual assistant remote',
  },
  {
    id: 'staf-akuntansi',
    title: 'Staf Akuntansi',
    field: 'Bisnis & Operasional',
    salaryMin: 4_500_000,
    salaryTypical: 6_500_000,
    entryFriendly: true,
    remoteFriendly: false,
    timeToEntry: '2–4 bulan',
    skills: ['akuntansi', 'pembukuan', 'excel', 'pajak'],
    description: 'Mencatat transaksi, menyusun laporan keuangan, dan mengurus kewajiban pajak perusahaan.',
    searchQuery: 'staff accounting staf akuntansi',
  },
  {
    id: 'sales-executive',
    title: 'Sales / Account Executive',
    field: 'Bisnis & Operasional',
    salaryMin: 5_000_000,
    salaryTypical: 9_000_000,
    entryFriendly: true,
    remoteFriendly: false,
    timeToEntry: '1–2 bulan',
    skills: ['sales', 'komunikasi', 'crm', 'presentasi'],
    description: 'Mencari dan menutup penjualan. Gaji pokoknya sedang, tapi komisi bisa mengangkat total pemasukan.',
    searchQuery: 'sales executive account executive',
  },
  {
    id: 'seo-specialist',
    title: 'SEO Specialist',
    field: 'Digital & Kreatif',
    salaryMin: 5_000_000,
    salaryTypical: 8_500_000,
    entryFriendly: false,
    remoteFriendly: true,
    timeToEntry: '3–5 bulan',
    skills: ['seo', 'copywriting', 'riset', 'visualisasi'],
    description: 'Membuat halaman perusahaan muncul di hasil pencarian Google tanpa harus membayar iklan.',
    searchQuery: 'seo specialist',
  },
  {
    id: 'digital-marketing',
    title: 'Digital Marketing Specialist',
    field: 'Digital & Kreatif',
    salaryMin: 6_000_000,
    salaryTypical: 10_000_000,
    entryFriendly: false,
    remoteFriendly: true,
    timeToEntry: '4–6 bulan',
    skills: ['meta-ads', 'google-ads', 'seo', 'content-planning', 'email-marketing', 'statistik'],
    description: 'Mengatur anggaran iklan digital dan mengukur hasilnya. Salah satu jalur tercepat menuju gaji dua digit.',
    searchQuery: 'digital marketing specialist performance marketing',
  },
  {
    id: 'qa-tester',
    title: 'QA Tester',
    field: 'Teknologi',
    salaryMin: 5_500_000,
    salaryTypical: 9_000_000,
    entryFriendly: true,
    remoteFriendly: true,
    timeToEntry: '3–5 bulan',
    skills: ['testing', 'riset', 'sql', 'manajemen-waktu'],
    description: 'Menguji aplikasi sebelum dirilis dan melaporkan kesalahan. Pintu masuk paling ramah ke industri teknologi.',
    searchQuery: 'qa tester quality assurance',
  },
  {
    id: 'ui-ux-designer',
    title: 'UI/UX Designer',
    field: 'Digital & Kreatif',
    salaryMin: 6_000_000,
    salaryTypical: 11_000_000,
    entryFriendly: false,
    remoteFriendly: true,
    timeToEntry: '5–8 bulan',
    skills: ['figma', 'riset', 'storytelling', 'presentasi'],
    description: 'Merancang alur dan tampilan aplikasi supaya mudah dipakai orang.',
    searchQuery: 'ui ux designer product designer',
  },
  {
    id: 'data-analyst',
    title: 'Data Analyst',
    field: 'Data',
    salaryMin: 7_000_000,
    salaryTypical: 12_000_000,
    entryFriendly: false,
    remoteFriendly: true,
    timeToEntry: '5–8 bulan',
    skills: ['sql', 'excel', 'visualisasi', 'statistik', 'python'],
    description: 'Mengubah data perusahaan jadi laporan dan rekomendasi yang bisa ditindaklanjuti.',
    searchQuery: 'data analyst',
  },
  {
    id: 'frontend-developer',
    title: 'Frontend Developer',
    field: 'Teknologi',
    salaryMin: 7_000_000,
    salaryTypical: 13_000_000,
    entryFriendly: false,
    remoteFriendly: true,
    timeToEntry: '6–9 bulan',
    skills: ['html-css', 'javascript', 'react', 'git', 'api'],
    description: 'Membangun tampilan situs dan aplikasi web yang dipakai langsung oleh pengguna.',
    searchQuery: 'frontend developer web developer',
  },
  {
    id: 'backend-developer',
    title: 'Backend Developer',
    field: 'Teknologi',
    salaryMin: 8_000_000,
    salaryTypical: 15_000_000,
    entryFriendly: false,
    remoteFriendly: true,
    timeToEntry: '8–12 bulan',
    skills: ['javascript', 'nodejs', 'database', 'api', 'git'],
    description: 'Membangun sistem di balik layar: server, basis data, dan alur data antar aplikasi.',
    searchQuery: 'backend developer software engineer',
  },
]
